### ISSUE TITLE
A question for video production

### ISSUE THREAD

**Issue by WeisongZhao** [AndrewGYork/high_na_single_objective_lightsheet#5]
Hi,

Great work, wonderful videos!
I wonder which kind of software can produce such hardware presentation video:
https://andrewgyork.github.io/high_na_single_objective_lightsheet/images/visual_abstract/visual_abstract.mp4
Could you tell me something about it?
Many thanks!

**Comment by AdvancedImagingUTSW** [comment]
Hi Weisong,

These videos are made using Blender by a Guru named Lachlan Whitehead:  https://twitter.com/DrLachie 

Best,
Kevin

**Comment by WeisongZhao** [comment]
Thank you Kevin,

The information you provided will help me a lot!

Best,
Weisong
